# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sortable_table"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Kovacs", "Oleg Vivtash"]
  s.date = "2012-06-26"
  s.description = "Rails 3 gem to produce a sortable, paginated, searchable table for any model"
  s.email = ""
  s.extra_rdoc_files = [
    "README",
    "TODO"
  ]
  s.files = [
    "Gemfile",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "example/controllers/cablecar/users_controller.rb",
    "example/models/cablecar/contact_info.rb",
    "example/models/cablecar/user.rb",
    "example/views/cablecar/users/index.html.erb",
    "images/arrow_down.gif",
    "images/arrow_up.gif",
    "images/logo_opaque.png",
    "install.rb",
    "lib/sortable/sortable_core.rb",
    "lib/sortable/sortable_helper.rb",
    "lib/sortable/version.rb",
    "lib/sortable_table.rb",
    "sortable_table.gemspec",
    "test/example_test_routing.rb",
    "test/test_helper.rb",
    "test/users_controller_test.rb",
    "views/sortable/_table.html.erb",
    "views/sortable/index.erb"
  ]
  s.homepage = "https://github.com/kovacs/sortable"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Rails 3 gem to produce a sortable, paginated, searchable table for any model"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sortable_table>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    else
      s.add_dependency(%q<sortable_table>, [">= 0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    end
  else
    s.add_dependency(%q<sortable_table>, [">= 0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
  end
end

