# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sortable_table}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Kovacs", "Oleg Vivtash"]
  s.date = %q{2011-02-10}
  s.description = %q{Rails 3 gem to produce a sortable, paginated, searchable table for any model}
  s.email = %q{}
  s.extra_rdoc_files = [
    "README",
    "TODO"
  ]
  s.files = [
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "example/controllers/cablecar/users_controller.rb",
    "example/models/cablecar/contact_info.rb",
    "example/models/cablecar/user.rb",
    "example/views/cablecar/users/index.html.erb",
    "images/arrow_down.gif",
    "images/arrow_up.gif",
    "images/logo_opaque.png",
    "install.rb",
    "lib/sortable/sortable_core.rb",
    "lib/sortable/sortable_helper.rb",
    "lib/sortable_table.rb",
    "sortable_table.gemspec",
    "test/example_test_routing.rb",
    "test/test_helper.rb",
    "test/users_controller_test.rb",
    "views/sortable/_table.html.erb",
    "views/sortable/index.erb"
  ]
  s.homepage = %q{https://github.com/kovacs/sortable}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails 3 gem to produce a sortable, paginated, searchable table for any model}
  s.test_files = [
    "test/example_test_routing.rb",
    "test/test_helper.rb",
    "test/users_controller_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    else
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    end
  else
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
  end
end

